name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v20
      - uses: cachix/cachix-action@v17
        with:
          name: hushmic-nix
          authToken: ${{ secrets.CACHIX_AUTH }}
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix flake check
