name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v20
      - uses: cachix/cachix-action@v17
        with:
          name: hushmic-nix
          authToken: ${{ secrets.CACHIX_AUTH }}
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix flake check
      - name: Pin current master build
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH }}
        run: |
          store_path="$(nix build .#hushmic --no-link --print-out-paths)"
          cachix push hushmic-nix "$store_path"
          cachix pin hushmic-nix latest "$store_path" --keep-revisions 1
